#!/bin/bash

read -p 'Address: ' address
read -p 'Subnet Mask: ' netmask
read -p 'Gateway: ' gateway
read -p 'DNS:' dns1 dns2 dns3
read -p 'Search:' search
read -p 'Domain: ' domain
read -p 'Interface Name: ' interface

cat > /etc/network/interfaces <<- EOL
auto lo
iface lo inet loopback

auto $interface
iface $interface inet static
	address $address
	netmask $netmask
	gateway $gateway
	dns-nameservers $dns1 $dns2 $dns3
	dns-search $search
	dns-domain $domain
EOL
cat > /etc/NetworkManager/NetworkManager.conf <<- EOL
	[main]
	plugins=ifupdown,keyfile,ofono
	#dns=dnsmasq
	[ifupdown]
	managed=true
EOL
touch /etc/network/interfaces.d/$interface
chmod 744  /etc/network/interfaces.d/$interface
ip addr flush $interface &&  systemctl restart networking.service
ifdown $interface &&  ifup $interface